#!/usr/bin/env python3
"""
guidance_generator.py — Post-Decision Guidance & Resource Finder
==================================================================
Runs AFTER an application's outcome is known (your tracker script calls
this with the outcome). Produces a personalized, actionable guide using a
local SLM, plus a fresh resource search via scraping:

  ACCEPTED              → "make the most of this" improvement guide +
                           complementary resources (financial literacy,
                           skill-building, related support).
  REJECTED /
  NO_PROGRAMS_FOUND     → "next steps" guide (incl. reapplication tips
                           where relevant) + a search for NGOs, charities,
                           and community/mutual-aid resources.

Everything runs locally except the optional web-search step, which only
ever sends generic category/location search terms — never personal
applicant details.

Intended call pattern (matches an external tracker script)
------------------------------------------------------------
  from guidance_generator import generate_guidance

  result = generate_guidance(
      program_applied_to=program,            # dict or name string
      application_result=outcome,            # "accepted" | "rejected" | "no_programs_found"
      previous_chat_profile=profile_or_report,
      conversations=[chat1_text, chat2_text],  # optional, multiple chats
  )

CLI usage
---------
  python guidance_generator.py accepted \\
      --program report.json --profile applicant_profile.json \\
      --conversation-file chat1.txt -o guide.md

  python guidance_generator.py rejected \\
      --program '{"name": "Illinois Family Food Support Program"}' \\
      --profile - < applicant_profile.json

Options
-------
  application_result          accepted | rejected | no_programs_found (free text OK)
  --program PATH_or_JSON_or_NAME   Program applied to (file, JSON string, or plain name)
  --profile PATH_or_-          Previous chat profile / assistance_finder report (default: stdin)
  --conversation-file PATH     Conversation transcript file (repeatable)
  --conversation-text TEXT     Conversation transcript inline text (repeatable)
  --location STATE             Override/seed location
  --backend / --host / --model / --temperature / --max-tokens / --timeout
                                Same as process_parse.py / assistance_finder.py
  --no-web-search               Disable the resource-search step
  --max-resources N             Cap on scraped resources (default: 4)
  -o, --output PATH             Save report to file
  --output-format markdown|json (default: markdown)
  --quiet / -q
"""

import argparse
import json
import sys
import textwrap
import time
from pathlib import Path
from typing import Optional


# Reuse existing infrastructure
sys.path.insert(0, str(Path(__file__).resolve().parent))
try:
    from process_parse import BACKENDS, build_backend, _try_parse_json, _fix_stdout_encoding
    from assistance_finder import (
        normalize_state, CATEGORY_SEARCH_TERMS, duckduckgo_search, fetch_page_text,
        call_llm_json, build_applicant_profile, summarize_conversations,
    )
except ImportError:
    sys.exit(
        "[ERROR] Could not import process_parse.py / assistance_finder.py.\n"
        "Place guidance_generator.py in the same directory as both files."
    )


# Logging
def log(msg: str, quiet: bool = False):
    if not quiet:
        print(f"[guidance_generator] {msg}", file=sys.stderr, flush=True)



# Constants
GUIDANCE_DISCLAIMER = (
    "This guidance was generated by a local language model for informational "
    "purposes only. It is not professional, legal, medical, tax, or "
    "immigration advice. Community/NGO resources listed here were found via "
    "automated web search and have NOT been independently vetted — confirm "
    "details directly before relying on them. In the United States, dialing "
    "2-1-1 connects to a free local helpline that can help verify and "
    "navigate options in person."
)

COMMUNITY_SEARCH_SUFFIX_BY_FOCUS = {
    "support": "NGO nonprofit community organization charity mutual aid",
    "complementary": "community resources financial literacy support programs",
}

OUTCOME_TITLES = {
    "accepted": "Next Steps — Application Accepted",
    "rejected": "Next Steps — Application Not Approved",
    "no_programs_found": "Next Steps — No Matching Program Found",
}


# Outcome / reference normalization
def normalize_outcome(application_result: Optional[str]) -> str:
    s = (application_result or "").strip().lower()
    if s in {"accepted", "approved", "accept", "approve"}:
        return "accepted"
    if s in {"rejected", "denied", "reject", "deny"}:
        return "rejected"
    if s in {"no_programs_found", "none", "not_found", "no_program", "no_programs"}:
        return "no_programs_found"
    if "accept" in s or "approv" in s:
        return "accepted"
    if "reject" in s or "den" in s:
        return "rejected"
    return "no_programs_found"


def _normalize_program_ref(program_applied_to) -> dict:
    if isinstance(program_applied_to, dict):
        return {
            "name": program_applied_to.get("program_name") or program_applied_to.get("name"),
            "category": program_applied_to.get("category", []),
            "official_url": program_applied_to.get("official_url"),
        }
    if program_applied_to:
        return {"name": str(program_applied_to), "category": [], "official_url": None}
    return {"name": None, "category": [], "official_url": None}


def _resolve_profile(previous_chat_profile, conversations: list, backend, quiet: bool) -> dict:
    """
    Accepts: an already-built applicant profile, a full assistance_finder
    report (extracts .applicant_profile), or raw document/profile data
    (builds a fresh profile from it).
    """
    if isinstance(previous_chat_profile, dict):
        if "applicant_profile" in previous_chat_profile:
            return previous_chat_profile["applicant_profile"]
        if "summary" in previous_chat_profile and "needed_categories" in previous_chat_profile:
            return previous_chat_profile
    return build_applicant_profile(previous_chat_profile, conversations or [], backend, quiet)



# Guide generation prompts
SYSTEM_PROMPT_IMPROVEMENT_GUIDE = textwrap.dedent("""\
    You are a supportive, practical case-management assistant. The person
    has just been ACCEPTED into an assistance program. Using their profile
    and any recent context, write a personalized, encouraging, and concrete
    guide to help them get the most out of this benefit and keep improving
    their overall situation (financial stability, complementary resources,
    building toward independence). Be specific and actionable — avoid
    generic platitudes. Do NOT give legal, medical, tax, or immigration
    advice; point them to the right kind of professional for that instead.

    Respond with ONLY a JSON object using exactly this schema:
    {
      "title": string,
      "summary": string,
      "action_steps": [
        {"step": string, "why_it_helps": string, "timeframe": string|null}
      ],
      "additional_resources": [string],
      "watch_outs": [string]
    }
""")

SYSTEM_PROMPT_ALTERNATIVE_GUIDE = textwrap.dedent("""\
    You are a supportive, practical case-management assistant. The person's
    application was not approved (or no formal program matched their
    situation). Using their profile and any recent context, write an
    honest, encouraging, and concrete guide for next steps that does NOT
    depend on the program they couldn't access — including, if relevant,
    ways to strengthen a future application, other avenues to pursue in
    the meantime, and practical steps to improve their situation today.
    Do not make false promises. Do NOT give legal, medical, tax, or
    immigration advice; point them to the right kind of professional for
    that instead.

    Respond with ONLY a JSON object using exactly this schema:
    {
      "title": string,
      "summary": string,
      "action_steps": [
        {"step": string, "why_it_helps": string, "timeframe": string|null}
      ],
      "reapplication_tips": [string] | null,
      "watch_outs": [string]
    }
""")

SYSTEM_PROMPT_EXTRACT_COMMUNITY_RESOURCE = textwrap.dedent("""\
    You extract structured information about a community resource, NGO, or
    charity that could help someone in need, from raw web page text.
    Respond with ONLY a JSON object using exactly this schema:
    {
      "name": string|null,
      "type": one of ["ngo","community_organization","charity",
                       "mutual_aid","religious_organization","other"],
      "category": [string],
      "description": string,
      "how_to_access": string,
      "contact_info": string|null,
      "notes": string
    }
    If the page text does not actually describe a specific organization or
    resource that could help, respond with {"name": null}.
    Use ONLY information present in the text — do not invent details.
""")


def _fallback_guide(raw: str) -> dict:
    return {
        "title": "Guidance",
        "summary": raw.strip()[:1000],
        "action_steps": [],
        "additional_resources": [],
        "watch_outs": [],
        "_parse_failed": True,
    }


def build_improvement_guide(profile: dict, program: dict, recent_context: str,
                            backend, quiet: bool) -> dict:
    user_prompt = (
        f"=== Applicant profile ===\n{json.dumps(profile, indent=2, ensure_ascii=False)}\n\n"
        f"=== Program just accepted into ===\n{json.dumps(program, indent=2, ensure_ascii=False)}\n\n"
        f"=== Recent context (if any) ===\n{recent_context or '(none)'}"
    )
    log("Generating improvement guide…", quiet)
    parsed, raw = call_llm_json(backend, SYSTEM_PROMPT_IMPROVEMENT_GUIDE, user_prompt, quiet)
    return parsed if parsed is not None else _fallback_guide(raw)


def build_alternative_guide(profile: dict, program: dict, outcome: str, recent_context: str,
                            backend, quiet: bool) -> dict:
    context_note = (
        f"Their application to '{program.get('name')}' was not approved."
        if outcome == "rejected" else
        "No formal assistance program in the database matched their situation."
    )
    user_prompt = (
        f"=== Applicant profile ===\n{json.dumps(profile, indent=2, ensure_ascii=False)}\n\n"
        f"=== Context ===\n{context_note}\n\n"
        f"=== Recent context (if any) ===\n{recent_context or '(none)'}"
    )
    log("Generating alternative-support guide…", quiet)
    parsed, raw = call_llm_json(backend, SYSTEM_PROMPT_ALTERNATIVE_GUIDE, user_prompt, quiet)
    return parsed if parsed is not None else _fallback_guide(raw)



# Community / NGO resource search (reuses assistance_finder's scrapers)
def extract_community_resource(text: str, url: str, category: str, backend, quiet: bool) -> Optional[dict]:
    if not text or len(text) < 200:
        return None
    user_prompt = f"URL: {url}\nLikely category: {category}\n\n=== Page text ===\n{text[:6000]}"
    parsed, _raw = call_llm_json(backend, SYSTEM_PROMPT_EXTRACT_COMMUNITY_RESOURCE, user_prompt, quiet)
    if not parsed or not parsed.get("name"):
        return None
    parsed["source_url"] = url
    parsed.setdefault("category", [category])
    return parsed


def search_community_support(needed_categories: list, location_str: str, backend, quiet: bool,
                             max_total: int = 4, max_per_category: int = 2,
                             focus: str = "support") -> list:
    log(f"Searching for community / NGO resources (focus={focus})…", quiet)
    found = []
    seen_urls = set()
    suffix = COMMUNITY_SEARCH_SUFFIX_BY_FOCUS.get(focus, COMMUNITY_SEARCH_SUFFIX_BY_FOCUS["support"])

    for category in needed_categories:
        if len(found) >= max_total:
            break
        term = CATEGORY_SEARCH_TERMS.get(category, category)
        query = f"{term} {location_str} {suffix} -site:.gov".strip()
        log(f"  Searching: {query}", quiet)
        results = duckduckgo_search(query, max_results=max_per_category + 2)

        count = 0
        for r in results:
            if count >= max_per_category or len(found) >= max_total:
                break
            url = r["url"]
            if url in seen_urls:
                continue
            seen_urls.add(url)
            log(f"    Fetching: {url}", quiet)
            text = fetch_page_text(url)
            resource = extract_community_resource(text, url, category, backend, quiet)
            if resource:
                found.append(resource)
                count += 1
            time.sleep(0.5)  # be polite

    return found



# Orchestrator
def generate_guidance(
    program_applied_to,
    application_result: str,
    previous_chat_profile,
    conversations: Optional[list] = None,
    location: Optional[str] = None,
    backend=None,
    enable_web_search: bool = True,
    max_resources: int = 4,
    quiet: bool = False,
    backend_name: Optional[str] = None,
    host: Optional[str] = None,
    model: str = "",
    temperature: float = 0.3,
    max_tokens: int = 4096,
    timeout: int = 1000,
) -> dict:
    """
    Main entry point — designed to be called from an application-tracker
    script as: generate_guidance(program_applied_to, application_result,
    previous_chat_profile, conversations=...)
    """
    if backend is None:
        backend = build_backend(backend_name, host, model, temperature, max_tokens, timeout, quiet)

    outcome = normalize_outcome(application_result)
    program = _normalize_program_ref(program_applied_to)
    profile = _resolve_profile(previous_chat_profile, conversations or [], backend, quiet)

    recent_context = summarize_conversations(conversations or [], backend, quiet) if conversations else ""

    state_code = normalize_state(location) or normalize_state((profile.get("location") or {}).get("state"))
    needed_categories = profile.get("needed_categories") or ["general"]
    location_str = state_code or (location or "")

    if outcome == "accepted":
        guide = build_improvement_guide(profile, program, recent_context, backend, quiet)
        focus = "complementary"
    else:
        guide = build_alternative_guide(profile, program, outcome, recent_context, backend, quiet)
        focus = "support"

    community_resources = []
    if enable_web_search:
        community_resources = search_community_support(
            needed_categories, location_str, backend, quiet,
            max_total=max_resources, focus=focus,
        )

    return {
        "outcome": outcome,
        "program_applied_to": program,
        "applicant_summary": profile.get("summary"),
        "guide": guide,
        "community_resources": community_resources,
        "disclaimer": GUIDANCE_DISCLAIMER,
    }



# Report formatting
def format_guidance_markdown(result: dict) -> str:
    outcome = result["outcome"]
    guide = result["guide"]
    lines = [f"# {OUTCOME_TITLES.get(outcome, 'Guidance Report')}", ""]

    program_name = (result.get("program_applied_to") or {}).get("name")
    if program_name:
        lines.append(f"**Program:** {program_name}")
    lines.append(f"**Applicant summary:** {result.get('applicant_summary') or 'n/a'}")
    lines.append("")

    lines.append(f"## {guide.get('title', 'Guide')}")
    lines.append(guide.get("summary", ""))
    lines.append("")

    if guide.get("action_steps"):
        lines.append("### Action steps")
        for s in guide["action_steps"]:
            tf = f" _({s.get('timeframe')})_" if s.get("timeframe") else ""
            lines.append(f"- **{s.get('step')}**{tf} — {s.get('why_it_helps')}")
        lines.append("")

    if guide.get("reapplication_tips"):
        lines.append("### If you want to reapply or appeal")
        for t in guide["reapplication_tips"]:
            lines.append(f"- {t}")
        lines.append("")

    if guide.get("additional_resources"):
        lines.append("### Additional resources")
        for r in guide["additional_resources"]:
            lines.append(f"- {r}")
        lines.append("")

    if guide.get("watch_outs"):
        lines.append("### Things to watch out for")
        for w in guide["watch_outs"]:
            lines.append(f"- {w}")
        lines.append("")

    if result.get("community_resources"):
        lines.append("## Community & NGO Resources")
        lines.append(
            "_Found via automated web search — not vetted. Confirm details "
            "before relying on them._"
        )
        lines.append("")
        for res in result["community_resources"]:
            lines.append(f"### {res.get('name')}")
            lines.append(f"_Type: {res.get('type', 'organization')}_")
            lines.append(res.get("description", ""))
            if res.get("how_to_access"):
                lines.append(f"**How to access:** {res['how_to_access']}")
            if res.get("contact_info"):
                lines.append(f"**Contact:** {res['contact_info']}")
            if res.get("source_url"):
                lines.append(f"Source: {res['source_url']}")
            lines.append("")

    lines.append("---")
    lines.append(result["disclaimer"])
    return "\n".join(lines)



# CLI
def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="guidance_generator.py",
        description="Generate a post-decision guidance report and find community resources.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    ap.add_argument("application_result", metavar="RESULT",
                    help="accepted | rejected | no_programs_found (free text accepted).")
    ap.add_argument("--program", metavar="PATH_OR_JSON_OR_NAME",
                    help="Program applied to: file path, inline JSON, or plain name.")
    ap.add_argument("--profile", default="-", metavar="PATH_OR_-",
                    help="Previous chat profile / assistance_finder report (default: stdin).")
    ap.add_argument("--conversation-file", action="append", default=[], metavar="PATH")
    ap.add_argument("--conversation-text", action="append", default=[], metavar="TEXT")
    ap.add_argument("--location", metavar="STATE")
    ap.add_argument("--backend", choices=list(BACKENDS.keys()))
    ap.add_argument("--host", metavar="URL")
    ap.add_argument("--model", default="", metavar="NAME")
    ap.add_argument("--temperature", type=float, default=0.3, metavar="F")
    ap.add_argument("--max-tokens", type=int, default=4096, metavar="N")
    ap.add_argument("--timeout", type=int, default= 1000, metavar="S")
    ap.add_argument("--max-resources", type=int, default=4, metavar="N")
    ap.add_argument("--no-web-search", action="store_true")
    ap.add_argument("-o", "--output", metavar="PATH")
    ap.add_argument("--output-format", choices=["markdown", "json"], default="markdown")
    ap.add_argument("--quiet", "-q", action="store_true")
    return ap


def main():
    _fix_stdout_encoding()
    ap = build_parser()
    args = ap.parse_args()

    # Resolve --program
    program_applied_to = None
    if args.program:
        p = Path(args.program)
        if p.exists():
            program_applied_to = json.loads(p.read_text(encoding="utf-8"))
        else:
            parsed = _try_parse_json(args.program)
            program_applied_to = parsed if parsed is not None else args.program

    # Resolve --profile
    if args.profile == "-":
        log("Reading previous chat profile from stdin…", args.quiet)
        raw_profile = sys.stdin.read()
    else:
        pp = Path(args.profile)
        if not pp.exists():
            sys.exit(f"[ERROR] Profile file not found: {args.profile}")
        raw_profile = pp.read_text(encoding="utf-8", errors="replace")
    previous_chat_profile = _try_parse_json(raw_profile)
    if previous_chat_profile is None:
        previous_chat_profile = raw_profile

    conversations = list(args.conversation_text)
    for cf in args.conversation_file:
        cp = Path(cf)
        if not cp.exists():
            sys.exit(f"[ERROR] Conversation file not found: {cf}")
        conversations.append(cp.read_text(encoding="utf-8", errors="replace"))

    try:
        backend = build_backend(
            args.backend, args.host, args.model,
            args.temperature, args.max_tokens, args.timeout, args.quiet,
        )
    except RuntimeError as exc:
        sys.exit(f"[ERROR] {exc}")

    log(f"Backend: {backend.name} @ {backend.host}  model={backend.model or '(server default)'}", args.quiet)

    result = generate_guidance(
        program_applied_to=program_applied_to,
        application_result=args.application_result,
        previous_chat_profile=previous_chat_profile,
        conversations=conversations,
        location=args.location,
        backend=backend,
        enable_web_search=not args.no_web_search,
        max_resources=args.max_resources,
        quiet=args.quiet,
    )

    output_text = (
        json.dumps(result, indent=2, ensure_ascii=False)
        if args.output_format == "json"
        else format_guidance_markdown(result)
    )

    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(output_text, encoding="utf-8")
        log(f"Saved: {out}", args.quiet)
    else:
        try:
            print(output_text)
        except UnicodeEncodeError:
            print(output_text.encode("utf-8", errors="replace").decode("utf-8"))


__all__ = [
    "generate_guidance", "normalize_outcome", "format_guidance_markdown",
    "search_community_support", "GUIDANCE_DISCLAIMER",
]

if __name__ == "__main__":
    main()